### ISSUE TITLE
Make bouncing at the end have more and more friction

### ISSUE THREAD

**Issue by malixsys** [nickmcmillan/react-physics-dragger#1]
On iOS devices, when you drag something past the end, the friction increases such that you usually cannot drag it to more dans half the width of the container...

**Comment by nickmcmillan** [comment]
Good call. I'll apply additional friction as the drag goes beyond the left or right boundaries. Hang tight...

**Comment by nickmcmillan** [comment]
Cool, deployed on npm as 1.0.7 
https://github.com/nickmcmillan/react-physics-dragger/pull/4
