### ISSUE TITLE
Feature Request: Ability to Page

### ISSUE THREAD

**Issue by ccveer** [nickmcmillan/react-physics-dragger#10]
We would like to add buttons to page through the slider.  Could this functionality be enabled?  We are willing to do the work if you would be willing to accept the PR.  Thanks!

**Comment by nickmcmillan** [comment]
I can certainly see the use for this, so I've had a stab at an implementation.
I think the best way to be able to control the dragger programatically is by exposing some kind of API via a `ref`. Basically what this React component does with Flickity (note the `<Flickity flickityRef={c => this.flkty = c}>`): https://github.com/theolampert/react-flickity-component#readme

Take a look at Example1 in this branch I've created which now features +/- positioning buttons. Curious what you think and whether this the right approach?

https://github.com/nickmcmillan/react-physics-dragger/tree/feature/set-position

**Comment by ccveer** [comment]
I think it looks good, but could we add an edge checker?  So that if you try to page past the edge of the slider, it slides back with friction?

**Comment by ccveer** [comment]
You could also fix it by changing setPosition as shown below in the file index.js
![image](https://user-images.githubusercontent.com/49158600/60602726-fe073680-9d79-11e9-80be-1c48ea5d11d9.png)

**Comment by ccveer** [comment]
This looks great!  Is there any chance this will be released soon?

**Comment by nickmcmillan** [comment]
Sorry it's taken a while to get here @ccveer !
I've completed some work and will create a PR now.

**Comment by nickmcmillan** [comment]
Ok merged. I've updated the docs too. Have deployed it to npm @`1.2.0`
