### ISSUE TITLE
Use hooks.

### ISSUE THREAD

**Issue by vaibhavhrt** [nickmcmillan/react-physics-dragger#2]
Use function components with hooks and hopefully achieve reduced bundle size.

**Comment by vaibhavhrt** [comment]
I would be happy to help to convert every class to function with hooks. I can help writing tests as well. Which one would you want me to do first. I think we should do tests first. I don't have much idea about testing in js, I am primarily python developer. I would need some help in what things needs to be tested. I have done some testing with jest in one my of React website.

**Comment by trblackw** [comment]
I’d be willing to help with this as well 👆🏼

**Comment by nickmcmillan** [comment]
@vaibhavhrt there's really no priority here. If you want to write some tests first then go for it! Probably should keep discussion in this issue related to hooks though.

There's only one class in this project - the `Dragger` class in `index.js`, but you're more than welcome to tackle converting that to use hooks.

**Comment by vaibhavhrt** [comment]
Since there is just one class, I will convert it to function first. Then I will create a new issue for tests. I will need some help from in writing tests.
