### ISSUE TITLE
Conversion to TypeScript

### ISSUE THREAD

**Issue by trblackw** [nickmcmillan/react-physics-dragger#5]
Would you be interested in potentially refactoring the codebase to TS? It wouldn't be that much of a process considering the size. I'd love to help you out with that if so!

**Comment by nickmcmillan** [comment]
Hi @trblackw - I'd be all for it. I haven't had a chance to get up to speed with TS yet so happy to let you take the lead. Only suggestion from me would be to wait until this PR is merged; https://github.com/nickmcmillan/react-physics-dragger/pull/3

**Comment by trblackw** [comment]
@nickmcmillan will do! Thanks man

**Comment by vaibhavhrt** [comment]
Yeah using typescript will be good, and eslint will stop complaining about missing type definitions.

**Comment by trblackw** [comment]
Yeah once #3 is merged that's when I'll start refactoring

**Comment by vaibhavhrt** [comment]
@trblackw if you want to do it all at once, then wait.
But if you want you can do it in parts too, I am changing `index.js` only in #3 . So you can do one file at a time, staring with anything but `index.js`.

**Comment by trblackw** [comment]
@vaibhavhrt Okay cool sounds good, I'll start working on it sometime this week, incrementally.

**Comment by trblackw** [comment]
@nickmcmillan any reason there's 2 eslintrc files? One within the root and one in src. I've never seen a project that requires two of them

**Comment by nickmcmillan** [comment]
It does seem weird, the project was scaffolded out using https://github.com/transitive-bullshit/create-react-library.

Worth mentioning is that create-react-library has a Typescript option when setting up a new project which could be worth an investigation.

**Comment by nickmcmillan** [comment]
https://github.com/nickmcmillan/react-physics-dragger/pull/3 is merged btw 🎉

**Comment by trblackw** [comment]
Crap I just realized that my forked copy of the repo didn’t reflect the
hook conversion in index.js (#3) when I converted it to TS. 🤦🏻‍♂️ What’s
the best way to go about resolving this conflict?

**Comment by vaibhavhrt** [comment]
Merge upstream/master into your master. There will be conflicts, resolve them. You will have to kinda write the whole `index.js` again.
Also you should not do stuff on the master of even your fork, should create a new branch, it can create some bit hard to fix problems sometimes.

**Comment by vaibhavhrt** [comment]
nvm there won't be many conflicts as you created a new file(of course). btw I am new to ts, can you explain why create `index.tsx` instead of `index.ts`

**Comment by trblackw** [comment]
Because JSX is returned. If the contents of a file were merely functional
and not a React component (React must be in scope if component renders JSX)
than it could be a .ts file, otherwise it has to be a .tsx file. I’ll work
on resolving the conflicts mentioned above over the weekend. You’re right
about not working on master of my forked branch. Hindsight’s 20/20!
