### ISSUE TITLE
Configure CI

### ISSUE THREAD

**Issue by vaibhavhrt** [nickmcmillan/react-physics-dragger#6]
Configure .travis.yml to run tests on travis.

**Comment by vaibhavhrt** [comment]
PR coming soon.

**Comment by nickmcmillan** [comment]
Forgive me I'm not too familiar with what travis is/does. What problem does this fix?

If it's regarding unit testing it appears that the tool used to scaffold this project (https://github.com/transitive-bullshit/create-react-library) uses Jest. Of course I could be mistaken!

**Comment by vaibhavhrt** [comment]
It runs the all tests you write automatically for every commit in a PR,
that way you know that the PR will not break anything without having to
test it manually. Of course we will have to write tests too.
You can also run eslint to make sure the code has proper formatting and the
code added in the PR follows your style guide.

**Comment by vaibhavhrt** [comment]
Travis can run any command for you on your repo, like `yarn test`, `yarn install` etc. Some people use it for automatic deployment as well, by running the deployment command when all tests pass.

**Comment by vaibhavhrt** [comment]
@trblackw does eslint works for ts too, or do we need some other linter.

**Comment by trblackw** [comment]
You use tslint which I’ve already added, including the related plugins

**Comment by trblackw** [comment]
In my pending PR I mean
